.TH update-ieee-data 8 "13 June 2014" "ieee-data"
.IX update-ieee-data

.SH NAME
update-ieee-data \- update data files from IEEE Standards Association such as the OUI and IAB lists

.SH SYNOPSIS
.B update-ieee-data

.SH DESCRIPTION
.B update-ieee-data
fetches the current version of the OUI and IAB lists from IEEE Standards Association
and installs it, if the installed versions is older than 5 days.

This utility requires curl, wget or libwww-perl to be installed.

.SH OPTIONS
.IP -q
Be quiet. Do not output messages.
.IP -f
Force the update, even if the file is newer than 5 days.

.SH FILES
.TP
.B /var/lib/ieee-data
Directory with the updated listings. 

.SH AUTHORS
Filippo Giunchedi <filippo@debian.org> and Luciano Bello <luciano@debian.org>.
